/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appointments;

import clinic.ClinicControler;
import clinic.Views;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dario R
 */
public class FrmWaitingRoom extends javax.swing.JFrame implements Views<Object> {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmWaitingRoom.class.getName());
 private ClinicControler controller;
 
    public FrmWaitingRoom(ClinicControler controller) {
        if (controller == null) {
            throw new IllegalArgumentException("El controlador es obligatorio");
        }
        this.controller = controller;
        controller.setView(this);
        initComponents();
        ShowData();
    }
    /**
     * Creates new form FrmWaitingRoom
     */
    public FrmWaitingRoom(){
        initComponents();
        controller = ClinicControler.getInstance(this);
        controller.setView(this);
        ShowData();        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        PnOption = new javax.swing.JPanel();
        BtnClear = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblRecord = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setTitle("WaitingRoom Daily List");
        jInternalFrame1.setVisible(true);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("WaitingRoom");

        PnOption.setBackground(new java.awt.Color(255, 255, 255));
        PnOption.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnClear.setText("Clear ");
        BtnClear.addActionListener(this::BtnClearActionPerformed);

        BtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Guardar.png"))); // NOI18N
        BtnSave.setText("Save");
        BtnSave.addActionListener(this::BtnSaveActionPerformed);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Buscar.png"))); // NOI18N
        jButton3.setText("Search ");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        BtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Eliminar.png"))); // NOI18N
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(this::BtnDeleteActionPerformed);

        javax.swing.GroupLayout PnOptionLayout = new javax.swing.GroupLayout(PnOption);
        PnOption.setLayout(PnOptionLayout);
        PnOptionLayout.setHorizontalGroup(
            PnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnOptionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BtnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnOptionLayout.setVerticalGroup(
            PnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnClear)
                    .addComponent(BtnSave)
                    .addComponent(jButton3)
                    .addComponent(BtnDelete))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        TblRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "ID", "Name", "Date", "Hour", "Status "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TblRecord.setToolTipText("");
        jScrollPane1.setViewportView(TblRecord);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel2))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(PnOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void ShowData() {
    DefaultTableModel model = (DefaultTableModel) TblRecord.getModel();
    model.setRowCount(0);

    Iterator<Appointment> it = controller.getAppointments();
    if (it == null) return;

    while (it.hasNext()) {
        Appointment cita = it.next();

        model.addRow(new Object[]{
            cita.getCode(),                   
            cita.getPatient().getId(),         
            cita.getPatient().getFullName(),   
            cita.getDate().toString(),        
            cita.getTime(),                   
            cita.getStatus().getStatus()       
        });
    }
}
        
    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
       TblRecord.clearSelection();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        String patientId = getSelectedValue(1, "Seleccione una cita para registrar al paciente.");
        if (patientId != null) controller.checkInPatient(patientId);
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        String code = getSelectedValue(0, "Seleccione una cita para cancelar.");
        if (code == null) return;

        int option = JOptionPane.showConfirmDialog(this,
                "¿Desea cancelar la cita " + code + "?", "Cancelar cita",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (option == JOptionPane.YES_OPTION) controller.cancelAppointment(code);
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String code = getSelectedValue(0, "Seleccione una cita para buscar.");
        if (code != null) controller.findAppointment(code);
    }//GEN-LAST:event_jButton3ActionPerformed

    private String getSelectedValue(int column, String warning) {
        int row = TblRecord.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, warning, "Sala de espera", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        Object value = TblRecord.getValueAt(row, column);
        if (value == null || value.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La fila seleccionada no tiene datos válidos.",
                    "Sala de espera", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return value.toString().trim(); 
    }

    @Override
    public void clear() {
        TblRecord.clearSelection();
    }

    @Override
    public void showData(Object data) {
        if (data instanceof String) {
            showMessage((String) data);
        }
        ShowData();
    }

    @Override
    public void showError(String error) {
        JOptionPane.showMessageDialog(this, error, "Sala de espera", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Sala de espera", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmWaitingRoom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnSave;
    private javax.swing.JPanel PnOption;
    private javax.swing.JTable TblRecord;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

